version: '3.8'
services:
  localstack:
    container_name: "LocalStack-s3"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566" #Edge port
      - "4569:4569" #Edge port
      - "4571:4571" #Edge port
      - "4572:4572" #Edge port
      - "4574:4574" #Edge port
      - "8083:8080" #Edge port
