spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:my-shop
    username: sa
    password: ${POSTGRES_PASSWORD}


  h2:
    console:
      enabled: true #http://localhost:8080/h2-console

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: false
