spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:my-shop}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=1m

app:
  scheduling:
    enabled: false
    period: 5000
    priceIncrease: 10.1
    optimization: true
    exclusive-lock: false

currency-service:
  host: http://localhost:8081
  methods:
    get-currency: /currency

