CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS warehouse (
    id             UUID PRIMARY KEY,
    name           VARCHAR,
    article_number BIGINT,
    description    VARCHAR,
    category_id    BIGINT REFERENCES categories (category_id) ON DELETE RESTRICT,
    price          INTEGER,
    quantity       INTEGER,
    last_update    TIMESTAMP(0),
    create_time    TIMESTAMP(0),
    CONSTRAINT uq_article_number UNIQUE (article_number)
);
